### ISSUE TITLE
ServerQuerier - Invalid value (65) for field 'response_type'

### ISSUE THREAD

**Issue by p-hennessy** [serverstf/python-valve#86]
It appears that after the most recent TF2 update; it included behind the scenes networking changes to SteamQuery.
I know very little about this but it appears to have joined Valve's anti-cheat network? I saw a GDC talk on this subject a number of years ago.

Here is the stack trace: 
```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/valve/source/messages.py", line 91, in validate
    raise ValueError
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "steamquery.py", line 9, in <module>
    info = get_srcds_server_info("us.tf2maps.net")
  File "steamquery.py", line 5, in get_srcds_server_info
    server_info = server.info()
  File "/usr/local/lib/python3.7/dist-packages/valve/source/a2s.py", line 140, in info
    return messages.InfoResponse.decode(self.get_response())
  File "/usr/local/lib/python3.7/dist-packages/valve/source/messages.py", line 415, in decode
    values[field.name], buffer = field.decode(buffer, values)
  File "/usr/local/lib/python3.7/dist-packages/valve/source/messages.py", line 41, in needs_buffer
    return func(self, buffer, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/valve/source/messages.py", line 131, in decode
    struct.unpack(self.format, field_data)[0]), left_overs)
  File "/usr/local/lib/python3.7/dist-packages/valve/source/messages.py", line 95, in validate
    value, self.name))
valve.source.messages.BrokenMessageError: Invalid value (65) for field 'response_type'
```

---

- **Python-valve Version(s)**:  0.2.1
- **Python Version(s)**: 3.8
- **Operating System(s)/Platform(s)**:  Ubuntu 20.04
- **Game Server(s) and Version(s)**:  Team Fortress 2
```ini
PatchVersion=6770799
ClientVersion=6770799
ServerVersion=6770799
ProductName=tf
appID=440
ServerAppID=232250
```

**Comment by Yepoleb** [comment]
Please switch to https://github.com/Yepoleb/python-a2s. This library will not be updated to support the protocol changes.
